name: dio_http_cache
description: http cache lib for Flutter dio like RxCache.It use sqflite as disk cache,and google/quiver-dart/LRU strategy as memory cache.
version: 0.3.0
homepage: https://github.com/hurshi/dio-http-cache

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.1
  dio: ^5.0.0
  
  json_annotation: ^4.5.0
  path: ^1.8.0
  quiver: ^3.0.1
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3
  build_runner: ^2.0.6

flutter:
  module:
    androidX: true
